# Generated by Django 4.2.16 on 2024-11-22 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersurvey',
            name='user_id',
        ),
    ]
