# Generated by Django 4.2.16 on 2024-11-21 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_userproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproduct',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='userproduct',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='UserProduct',
        ),
    ]
